name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.6.2

      - name: Check formatting
        run: deno fmt --check
